misitio/blog/urls.py
from django.urls import path, include
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views


app_name = 'blog'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('formulario', views.formulario, name ='formulario'),
    
    path('inicioSesion', views.inicioSesion , name='inicioSesion' ),
    path('success',views.success, name = 'usuario_success'),
    path('cerrarSeccion',views.cerrarSeccion, name = 'cerrarSeccion'),

    path('menu_admin', views.menu_admin , name='menu_admin' ),
    path('agregarPerro', views.agregarPerro , name='agregarPerro' ),
    path('listarPerro', views.listarPerro , name='listarPerro' ),
   
    path('eliminarPerro/<id>', views.eliminarPerro , name='eliminarPerro' ),
    path('modificarPerro/<id>', views.modificarPerro , name='modificarPerro' ),
    path('solicitudPerro/<id>', views.solicitudPerro , name='solicitudPerro' ),

    path('disponible', views.disponible, name='disponible'),
    path('rescatado', views.rescatado, name='rescatado'),
    path('adoptado', views.adoptado, name='adoptado'),
    path('todos', views.todos, name ="todos"),

    path('filtroDisponibleIndex', views.filtroDisponibleIndex, name = 'filtroDisponibleIndex'),
    path('filtroRescatadoIndex', views.filtroRescatadoIndex, name = 'filtroRescatadoIndex'),
    path('filtroAdoptadoIndex', views.filtroAdoptadoIndex, name = 'filtroAdoptadoIndex'),
    path('validador2/<id>', views.validador2, name = "validador2"),

    #path('password-reset',auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),name='password_reset'),
    #path('password-reset/done',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    #path('password-reset-confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),name='password_reset_confirm'),
    url('', include('pwa.urls')),
    url(r'^password_reset/$', auth_views.PasswordResetView, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView,name= 'password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.PasswordResetConfirmView,name='password_reset_confirm'),
    url(r'^reset/done', auth_views.PasswordResetCompleteView, name = 'password_reset_complete'),
    #path('solicitudPerro/<id>', views.solicitudPerro , name='solicitudPerro' ),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misitio/misitio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from rest_framework  import routers
from api import views


router = routers.DefaultRouter() 
router.register(r'formularioUserPerris', views.FormulariosUserViewSet)
router.register(r'user', views.UserViewSet)
urlpatterns = [
    path('',include('blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    url(r'^api/', include(router.urls), name= 'rest_framework')
]

misitio/blog/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class FormularioUserPerris(models.Model):
    email = models.EmailField()
    rut = models.OneToOneField(User,on_delete='models.CASCADE')
    nombre = models.CharField(max_length=50)
    segundoNombre = models.CharField(max_length=50)
    apellidoPaterno = models.CharField(max_length=50)
    apellidoMaterno = models.CharField(max_length=50)
    fechaNacimiento = models.DateField()
    fono = models.CharField(max_length=12)
    region = models.CharField(max_length=90)
    comuna = models.CharField(max_length=90)
    tipoCasa = models.CharField(max_length=30)
    tipo = models.CharField(max_length = 30)
    password_1 = models.CharField(max_length =250)  

    def create(self):
        self.save() 

    def __str__(self):
        return self.nombre + " " + self.apellidoPaterno + " " + self.apellidoMaterno

    


    

class MascotasPerro(models.Model):
    
    file = models.FileField(blank=True, null=True, upload_to="blog")
    nombrePerro = models.CharField(max_length = 30)
    razaPredominante = models.CharField(max_length = 50)
    descripcion = models.TextField()
    estado = models.CharField(max_length = 50)

    def __str__(self):
        return self.nombrePerro + " - "+ self.estado
    
    def create(self):
        self.save()

    




    

misitio/blog/views.py
from django.shortcuts import render,render_to_response, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import FormularioUserPerris, MascotasPerro
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse

# Create your views here.
# Create your views here.
def index(request):

    
    try:
        nombre = request.session['nombre']
        apellidoPaterno = request.session['apellidoPaterno']
        tipo = request.session['tipo']
        mascotas = MascotasPerro.objects.all()
        
        return render(request, 'blog/index.html', {'nombre':nombre,
                                                   'apellidoPaterno': apellidoPaterno,
                                                   'tipo':tipo,
                                                   'mascotas':mascotas})
    except:
        mascotas = MascotasPerro.objects.all()
        nombre = ""
        return render(request, 'blog/index.html', {'mascotas':mascotas,
                                                    'nombre': nombre})
        

        
    
    
    

def menu_admin(request):
    return render(request, 'blog/menu_admin.html', {})


def agregarPerro(request):

    if request.method == 'POST':
        #request.files = para obtener el archivo, averiguar
        mensaje = ""
        error = ""
        
        try:
            mascota = MascotasPerro()

            file = request.FILES['file']
            #ext = file.name.split(".")[-1]
            #file.name = str(mascota.pk) + "." + ext
            mascota.file = file
            mascota.save()
            mascota.nombrePerro = request.POST['nombre']
            
            mascota.razaPredominante = request.POST['raza']
            
            mascota.descripcion = request.POST['descripcion']
            
            mascota.estado = request.POST['estado']
            
            mascota.save()

            mensaje = "Animal almacenado correctamente"

            return render(request, 'mantenedor/agregarPerro.html', {'mensaje':mensaje,
                                                                    'nombre':request.session['nombre'],
                                                                    'apellidoPaterno':request.session['apellidoPaterno']})

        except Exception as e:
            error = "Error al guardar el perfil del perro: " + str(e)
            return render(request, 'mantenedor/agregarPerro.html', {'error': error,
                                                                    'nombre':request.session['nombre'],
                                                                    'apellidoPaterno':request.session['apellidoPaterno']})

        #a = Mascota.objects.create(fotografia = fotografia, nombrePerro = nombre, razaPredominante = raza, descripcion = descripcion, estado = estado)
        #a.save()
        
    else:
        return render(request, 'mantenedor/agregarPerro.html',{
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})
def listarPerro(request):

    mascotas = MascotasPerro.objects.all()

    return render(request, 'mantenedor/listarPerro.html',{'mascotas': mascotas,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})



def eliminarPerro(request, id):
    mascota = MascotasPerro.objects.get(id=id)

    try:
        mascota.delete()
        mensaje = "Animal fue eliminado Correctamente"
        messages.success(request, mensaje)
        return render(request,'blog:listaPerro',{'nombre':request.session['nombre'],
                                                             'apellido':request.session})
    except:
        
        return redirect('blog:listarPerro')
        
def modificarPerro(request,id):
    mascota = MascotasPerro.objects.get(id = id)
    if request.method == 'POST':
        #request.files = para obtener el archivo, averiguar
        mensaje = ""
        error = ""
        
        try:
            mascota = MascotasPerro()
            mascota.id = request.POST.get('txtId')
            file = request.FILES['file']
            

            


            mascota.file = file
            
            mascota.nombrePerro = request.POST['nombre']
            
            mascota.razaPredominante = request.POST['raza']
            
            mascota.descripcion = request.POST['descripcion']
            
            mascota.estado = request.POST['estado']
            
            mascota.save()

            mensaje = "Animal modificado correctamente"
            messages.success(request, mensaje)
            return redirect('blog:listarPerro')
            

        except Exception as e:
            mensaje = "Error al modificar el perfil del perro: " + str(e)
            messages.error(request, mensaje)
        return redirect('blog:listarPerro')
    
    return render(request, 'mantenedor/modificarPerro.html', {'mascota':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})
    
def disponible(request):
    a = "Disponible"
    mascota = MascotasPerro.objects.filter(estado = a)
    return render(request, 'mantenedor/listarPerro.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})

def adoptado(request):
    a = "Adoptado"
    mascota = MascotasPerro.objects.filter(estado = a)
    return render(request, 'mantenedor/listarPerro.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})

def rescatado(request):
    a = "Rescatado"
    mascota = MascotasPerro.objects.filter(estado = a)
    return render(request, 'mantenedor/listarPerro.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})

def todos(request):
    mascota = MascotasPerro.objects.all()
    return render(request, 'mantenedor/listarPerro.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']} )

def disponibleCliente(request):
    a = "Disponible"
    mascota = MascotasPerro.objects.filter(estado = a)
    return render(request, 'blog/mantenedor.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})

def adoptadoCliente(request):
    a = "Adoptado"
    mascota = MascotasPerro.objects.filter(estado = a)
    return render(request, 'blog/mantenedor.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})

def rescatadoCliente(request):
    a = "Rescatado"
    mascota = MascotasPerro.objects.filter(estado = a)
    return render(request, 'blog/mantenedor.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})

def filtroDisponibleIndex(request):
    a = "Disponible"
    mascotas = MascotasPerro.objects.filter(estado=a)

    try:
        return render(request, 'blog/index.html', {'disponibles':mascotas,
                                                'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})
        
    except:
        return render(request, 'blog/index.html', {'disponibles':mascotas,
                                                    'nombre':""})
    
    


def filtroRescatadoIndex(request):
    a = "Rescatado"
    mascotas = MascotasPerro.objects.filter(estado=a)
    try:
        return render(request, 'blog/index.html', {'rescatados':mascotas,
                                                'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})
        
    except:
        return render(request, 'blog/index.html', {'rescatados':mascotas})
    

def filtroAdoptadoIndex(request):
    a = "Adoptado"
    mascotas = MascotasPerro.objects.filter(estado=a)
    try:
        return render(request, 'blog/index.html', {'adoptados':mascotas,
                                                'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})
        
    except:
        return render(request, 'blog/index.html', {'adoptados':mascotas})

def formulario(request):
    if request.method =='POST':
        try:
            email = request.POST['email']
            rut = request.POST['username']
            password_1 = request.POST['password']


            b = User.objects.create_user(username =rut, password= password_1, email=email)
            b.save()

misitio/blog/templates/mantenedor/agregarPerro.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title%}
Formulario Registro
{% endblock%}

{% block css_script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!----<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'js/validacion_agregarMascota.js' %}"></script>
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/menu_admin.css' %}" />
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/agregarMascota.css' %}" />
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/ventanasEmerge.css' %}" />
{% endblock %}


{% block content %}
<div id="datos_user" class="row justify-content-center">
    <div class="col-4">
        <h1>Agregar Mascota</h1>
    </div>
</div>

<div class="container">
    <div class="col-12">
        {% if mensaje %}
        <div class="alert success">
            <span class="closebtn">&times;</span>
            <strong>Exito!</strong> {{mensaje}}
        </div>
        {% endif %}
    </div>
    <div class="col-12">
        {% if error %}
        <div class="alert warning">
            <span class="closebtn">&times;</span>
            <strong>Error!</strong> {{error}}
        </div>

        {% endif %}
    </div>
</div>

<form id="menu_agregarMascota" method='post' id="agregarPerro" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="row justify-content-center">
        <div class="col-6">
            <div class="form-group">
                <label for="file">Fotografia:</label>
                <input type="file" name="file" required>

            </div>

            <div class="form-group">
                <label for="nombre">Nombre:</label>
                <input name="nombre" type="text" class="form-control " id="nombre" placeholder="" required>
            </div>

            <div class="form-group">
                <label for="raza">Raza Predominante:</label>
                <input name="raza" type="text" class="form-control" id="raza" placeholder="" required>
            </div>
            <div class="form-group">
                <label for="descripcion">Descripción:</label>
                <input name="descripcion" type="text" class="form-control" id="descripcion" placeholder="" required>
            </div>
            <div class="form-group">
                <label for="estado">Estado</label>
                <select name="estado" class="form-control" id="estado" required>
                    <option selected>Seleccione</option>
                    <option>Disponible</option>
                    <option>Rescatado</option>
                    <option>Adoptado</option>

                </select>
            </div>
            <button id="btn_campana" type="submit" class="btn btn-primary">Enviar</button>
        </div>

    </div>
</form>

<script src="{% static 'js/mensajeEmergente.js' %}"></script>

</div>

{% endblock content %}

misitio/blog/templates/mantenedor/listarPerro.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title%}
Listar Mascotas
{% endblock%}

{% block css_script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!----<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'js/validacion_agregarMascota.js' %}"></script>
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/menu_admin.css' %}" />
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/ventanasEmerge.css' %}" />
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/listar_mascota.css' %}" />
{% endblock %}


{% block content %}

<div class="container">

    <div id="datos_user" class="row justify-content-center">
        <div class="col-4">
            <h1>Listar Mascota</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            {% if messages %}

            {% for m in messages %}
            <div class="alert success">
                <span class="closebtn">&times;</span>
                <strong>Exito!</strong> {{m}}
            </div>
            {% endfor %}

            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <h4>Filtrado Por:</h4>
        </div>
    </div>

    <div id="filtros" class="row">
        <div class="btn_filtro col-12 col-md-3 text-center">
            <a href="{% url 'blog:disponible' %}" class="btn btn btn-success btn-lg active" role="button" aria-pressed="true">Disponible</a>
        </div>
        <div class="btn_filtro col-12 col-md-3 text-center">
            <a href="{% url 'blog:rescatado' %}" class="btn btn-warning btn-lg active" role="button" aria-pressed="true">Rescatado</a>
        </div>
        <div class="btn_filtro col-12 col-md-3 text-center">
            <a href="{% url 'blog:adoptado' %}" class="btn btn-dark btn-lg active" role="button" aria-pressed="true">Adoptado</a>
        </div>

        <div class="btn_filtro col-12 col-md-3 text-center">
            <a href="{% url 'blog:todos' %}" class="btn btn-dark btn-lg active" role="button" aria-pressed="true">Todos</a>
        </div>
    </div>


    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Fotografia</th>
                <th scope="col">Nombre</th>
                <th scope="col">Raza</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Estado</th>
                <th scope="col">Eliminar</th>
                <th scope="col">Modificar</th>
            </tr>
        </thead>
        <tbody>
            {% for m in mascotas %}
            <tr>
                <td><img src="{{ MEDIA_URL}}{{ m.file}}" alt=""></a></td>
                <td>{{ m.nombrePerro }}</td>
                <td>{{ m.razaPredominante }}</td>
                <td>{{ m.descripcion}}</td>
                <td>{{ m.estado}}</td>
                <td>
                    <a href="{% url 'blog:eliminarPerro' m.id %}" class="btn btn-danger btn-sm active" role="button"
                        aria-pressed="true">Eliminar</a>
                </td>
                <td>
                    <a href="{% url 'blog:modificarPerro' m.id %}" class="btn btn-light btn-sm active" role="button"
                    aria-pressed="true">Modificar</a>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>

</div>


<script src="{% static 'js/mensajeEmergente.js' %}"></script>


{% endblock content %}

misitio/blog/templates/mantenedor/modificarPerro.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title%}
Formulario Registro
{% endblock%}

{% block css_script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!----<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'js/validacion_agregarMascota.js' %}"></script>
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/menu_admin.css' %}" />
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/agregarMascota.css' %}" />
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/ventanasEmerge.css' %}" />
{% endblock %}


{% block content %}
<div id="datos_user" class="row justify-content-center">
    <div class="col-4">
        <h1>Modificar Mascota</h1>
    </div>
</div>


<form method='post' id="modificarPerro" enctype="multipart/form-data" >
    {% csrf_token %}
<div class="row justify-content-center">
    <div class="col-6">
            <input type="hidden" name="txtId" id="txtId" value = "{{ mascota.id}}"> 
            <div class="form-group">
                <label for="file">Fotografia:</label>
                <input type="file" name="file" value="{{mascota.file}}" required>
                
            </div>

            <div class="form-group">
                <label for="nombre">Nombre:</label>
                <input name="nombre" type="text" class="form-control " id="nombre" value="{{ mascota.nombrePerro}}" placeholder="" required>
            </div>

            <div class="form-group">
                <label for="raza">Raza Predominante:</label>
                <input name="raza" type="text" class="form-control" id="raza" value="{{ mascota.razaPredominante}}" placeholder="" required>                                
            </div>
            <div class="form-group">
                <label for="descripcion">Descripción:</label>
                <input name="descripcion" type="text" class="form-control" id="descripcion" value="{{ mascota.descripcion}}" placeholder="" required>
            </div>
            <div class="form-group">
                <label for="estado">Estado</label>
                <select name="estado" class="form-control" id="estado" required>
                    
                    <option>Seleccione</option>
                    <option {% if mascota.estado == "Disponible"%}
                    {{'selected'}}
                    {% endif 
                        %} 
                    >Disponibled</option>
                    <option
                    {% if mascota.estado == "Rescatado"%}
                    {{'selected'}}
                    {% endif%}>Rescatado</option>
                    <option
                    {% if mascota.estado == "Adoptado"%}
                    {{'selected'}}
                    {% endif%}>Adoptado</option>
                    
                </select>
            </div>
            

            

        

            <button id="btn_campana" type="submit" class="btn btn-primary">Modificar</button>
    </div>

</div>
</form>    

<script src="{% static 'js/mensajeEmergente.js' %}"></script>

</div>

{% endblock content %}

misitio/blog/templates/mantenedor/respaldo_listarPerro.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />  
    <link rel="stylesheet" href="{% static 'css/ventanasEmerge.css' %}">
</head>
<body>
    <h1>Listar Perro</h1>
    
    {% if mensaje %}
        <div class="alert success">
            <span class="closebtn">&times;</span>  
            <strong>Exito!</strong> {{mensaje}}
        </div>
    {% endif %}
    {% if error %}
    
            <div class="alert warning">
                <span class="closebtn">&times;</span>  
                <strong>Error!</strong> {{error}}
            </div>
        
    {% endif %}
    
    <table>
        <tr>
            <th>Fotografia</th>
            <th>Nombre</th>
            <th>Raza</th>
            <th>Descripcion</th>
            <th>Estado</th>

        </tr>
        {% for m in mascotas %}
            <tr>
                <td><a href="">{{ m.file}}</a></td>
                <td>{{ m.nombrePerro }}</td>
                <td>{{ m.razaPredominante }}</td>
                <td>{{ m.descripcion}}</td>
                <td>{{ m.estado}}</td>
                <td><a href="{% url 'blog:eliminarPerro' m.id %}">Eliminar</a></td>
                <td><a href="">Modificar</a></td>
                
            </tr>
                
        {% endfor %}
    </table>

    <a href="{% url 'blog:mantenedorIndex' %}">Atrás</a>
    
    <script src="{% static 'js/mensajeEmergente.js' %}"></script>
</body>
</html>

misitio/blog/templates/mantenedor/solicitud.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title%}
Solicitud De adopcion
{% endblock%}

{% block css_script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!----<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'js/rut.js' %}"></script>
<script src="{% static 'js/cargar_regionComuna2.js' %}"></script>
<script src="{% static 'js/validacion_form.js' %}"></script>
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/formulario.css' %}" />
{% endblock %}


{% block content %}

<div class="row justify-content-center">
    
</div>
<form method='post' id="formulario">
    {% csrf_token %}
    <div class="row justify-content-center">
        <div class="col-6">

            
                
                <input name="user_name" type="hidden" class="form-control" id="email">
                <input name="nombreMascota" type="hidden" class="form-control" id="email" >
                <input name="id_Mascota" type="hidden" class="form-control" id="email" >
                
                <h1>¡Solicitud enviada!</h1>
                <h3>Nos contactaremos contigo mediante email. Esperamos encontrar un hogar a los perritos!</h3>
            
            

            
        </div>

    </div>
</form>

{% endblock content %}