misitio/blog/urls.py
from django.urls import path, include
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views


app_name = 'blog'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('formulario', views.formulario, name ='formulario'),
    
    path('inicioSesion', views.inicioSesion , name='inicioSesion' ),
    path('success',views.success, name = 'usuario_success'),
    path('cerrarSeccion',views.cerrarSeccion, name = 'cerrarSeccion'),

    path('menu_admin', views.menu_admin , name='menu_admin' ),
    path('agregarPerro', views.agregarPerro , name='agregarPerro' ),
    path('listarPerro', views.listarPerro , name='listarPerro' ),
   
    path('eliminarPerro/<id>', views.eliminarPerro , name='eliminarPerro' ),
    path('modificarPerro/<id>', views.modificarPerro , name='modificarPerro' ),
    path('solicitudPerro/<id>', views.solicitudPerro , name='solicitudPerro' ),

    path('disponible', views.disponible, name='disponible'),
    path('rescatado', views.rescatado, name='rescatado'),
    path('adoptado', views.adoptado, name='adoptado'),
    path('todos', views.todos, name ="todos"),

    path('filtroDisponibleIndex', views.filtroDisponibleIndex, name = 'filtroDisponibleIndex'),
    path('filtroRescatadoIndex', views.filtroRescatadoIndex, name = 'filtroRescatadoIndex'),
    path('filtroAdoptadoIndex', views.filtroAdoptadoIndex, name = 'filtroAdoptadoIndex'),
    path('validador2/<id>', views.validador2, name = "validador2"),

    #path('password-reset',auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),name='password_reset'),
    #path('password-reset/done',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    #path('password-reset-confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),name='password_reset_confirm'),
    url('', include('pwa.urls')),
    url(r'^password_reset/$', auth_views.PasswordResetView, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView,name= 'password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.PasswordResetConfirmView,name='password_reset_confirm'),
    url(r'^reset/done', auth_views.PasswordResetCompleteView, name = 'password_reset_complete'),
    #path('solicitudPerro/<id>', views.solicitudPerro , name='solicitudPerro' ),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misitio/misitio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from rest_framework  import routers
from api import views


router = routers.DefaultRouter() 
router.register(r'formularioUserPerris', views.FormulariosUserViewSet)
router.register(r'user', views.UserViewSet)
urlpatterns = [
    path('',include('blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    url(r'^api/', include(router.urls), name= 'rest_framework')
]

misitio/blog/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class FormularioUserPerris(models.Model):
    email = models.EmailField()
    rut = models.OneToOneField(User,on_delete='models.CASCADE')
    nombre = models.CharField(max_length=50)
    segundoNombre = models.CharField(max_length=50)
    apellidoPaterno = models.CharField(max_length=50)
    apellidoMaterno = models.CharField(max_length=50)
    fechaNacimiento = models.DateField()
    fono = models.CharField(max_length=12)
    region = models.CharField(max_length=90)
    comuna = models.CharField(max_length=90)
    tipoCasa = models.CharField(max_length=30)
    tipo = models.CharField(max_length = 30)
    password_1 = models.CharField(max_length =250)  

    def create(self):
        self.save() 

    def __str__(self):
        return self.nombre + " " + self.apellidoPaterno + " " + self.apellidoMaterno

    


    

class MascotasPerro(models.Model):
    
    file = models.FileField(blank=True, null=True, upload_to="blog")
    nombrePerro = models.CharField(max_length = 30)
    razaPredominante = models.CharField(max_length = 50)
    descripcion = models.TextField()
    estado = models.CharField(max_length = 50)

    def __str__(self):
        return self.nombrePerro + " - "+ self.estado
    
    def create(self):
        self.save()

    




    

misitio/blog/views.py
from django.shortcuts import render,render_to_response, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import FormularioUserPerris, MascotasPerro
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse

# Create your views here.
# Create your views here.
def index(request):

    
    try:
        nombre = request.session['nombre']
        apellidoPaterno = request.session['apellidoPaterno']
        tipo = request.session['tipo']
        mascotas = MascotasPerro.objects.all()
        
        return render(request, 'blog/index.html', {'nombre':nombre,
                                                   'apellidoPaterno': apellidoPaterno,
                                                   'tipo':tipo,
                                                   'mascotas':mascotas})
    except:
        mascotas = MascotasPerro.objects.all()
        nombre = ""
        return render(request, 'blog/index.html', {'mascotas':mascotas,
                                                    'nombre': nombre})
        

        
    
    
    

def menu_admin(request):
    return render(request, 'blog/menu_admin.html', {})


def agregarPerro(request):

    if request.method == 'POST':
        #request.files = para obtener el archivo, averiguar
        mensaje = ""
        error = ""
        
        try:
            mascota = MascotasPerro()

            file = request.FILES['file']
            #ext = file.name.split(".")[-1]
            #file.name = str(mascota.pk) + "." + ext
            mascota.file = file
            mascota.save()
            mascota.nombrePerro = request.POST['nombre']
            
            mascota.razaPredominante = request.POST['raza']
            
            mascota.descripcion = request.POST['descripcion']
            
            mascota.estado = request.POST['estado']
            
            mascota.save()

            mensaje = "Animal almacenado correctamente"

            return render(request, 'mantenedor/agregarPerro.html', {'mensaje':mensaje,
                                                                    'nombre':request.session['nombre'],
                                                                    'apellidoPaterno':request.session['apellidoPaterno']})

        except Exception as e:
            error = "Error al guardar el perfil del perro: " + str(e)
            return render(request, 'mantenedor/agregarPerro.html', {'error': error,
                                                                    'nombre':request.session['nombre'],
                                                                    'apellidoPaterno':request.session['apellidoPaterno']})

        #a = Mascota.objects.create(fotografia = fotografia, nombrePerro = nombre, razaPredominante = raza, descripcion = descripcion, estado = estado)
        #a.save()
        
    else:
        return render(request, 'mantenedor/agregarPerro.html',{
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})
def listarPerro(request):

    mascotas = MascotasPerro.objects.all()

    return render(request, 'mantenedor/listarPerro.html',{'mascotas': mascotas,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})



def eliminarPerro(request, id):
    mascota = MascotasPerro.objects.get(id=id)

    try:
        mascota.delete()
        mensaje = "Animal fue eliminado Correctamente"
        messages.success(request, mensaje)
        return render(request,'blog:listaPerro',{'nombre':request.session['nombre'],
                                                             'apellido':request.session})
    except:
        
        return redirect('blog:listarPerro')
        
def modificarPerro(request,id):
    mascota = MascotasPerro.objects.get(id = id)
    if request.method == 'POST':
        #request.files = para obtener el archivo, averiguar
        mensaje = ""
        error = ""
        
        try:
            mascota = MascotasPerro()
            mascota.id = request.POST.get('txtId')
            file = request.FILES['file']
            

            


            mascota.file = file
            
            mascota.nombrePerro = request.POST['nombre']
            
            mascota.razaPredominante = request.POST['raza']
            
            mascota.descripcion = request.POST['descripcion']
            
            mascota.estado = request.POST['estado']
            
            mascota.save()

            mensaje = "Animal modificado correctamente"
            messages.success(request, mensaje)
            return redirect('blog:listarPerro')
            

        except Exception as e:
            mensaje = "Error al modificar el perfil del perro: " + str(e)
            messages.error(request, mensaje)
        return redirect('blog:listarPerro')
    
    return render(request, 'mantenedor/modificarPerro.html', {'mascota':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})
    
def disponible(request):
    a = "Disponible"
    mascota = MascotasPerro.objects.filter(estado = a)
    return render(request, 'mantenedor/listarPerro.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})

def adoptado(request):
    a = "Adoptado"
    mascota = MascotasPerro.objects.filter(estado = a)
    return render(request, 'mantenedor/listarPerro.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})

def rescatado(request):
    a = "Rescatado"
    mascota = MascotasPerro.objects.filter(estado = a)
    return render(request, 'mantenedor/listarPerro.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})

def todos(request):
    mascota = MascotasPerro.objects.all()
    return render(request, 'mantenedor/listarPerro.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']} )

def disponibleCliente(request):
    a = "Disponible"
    mascota = MascotasPerro.objects.filter(estado = a)
    return render(request, 'blog/mantenedor.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})

def adoptadoCliente(request):
    a = "Adoptado"
    mascota = MascotasPerro.objects.filter(estado = a)
    return render(request, 'blog/mantenedor.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})

def rescatadoCliente(request):
    a = "Rescatado"
    mascota = MascotasPerro.objects.filter(estado = a)
    return render(request, 'blog/mantenedor.html',{'mascotas':mascota,
                                                          'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})

def filtroDisponibleIndex(request):
    a = "Disponible"
    mascotas = MascotasPerro.objects.filter(estado=a)

    try:
        return render(request, 'blog/index.html', {'disponibles':mascotas,
                                                'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})
        
    except:
        return render(request, 'blog/index.html', {'disponibles':mascotas,
                                                    'nombre':""})
    
    


def filtroRescatadoIndex(request):
    a = "Rescatado"
    mascotas = MascotasPerro.objects.filter(estado=a)
    try:
        return render(request, 'blog/index.html', {'rescatados':mascotas,
                                                'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})
        
    except:
        return render(request, 'blog/index.html', {'rescatados':mascotas})
    

def filtroAdoptadoIndex(request):
    a = "Adoptado"
    mascotas = MascotasPerro.objects.filter(estado=a)
    try:
        return render(request, 'blog/index.html', {'adoptados':mascotas,
                                                'nombre':request.session['nombre'],
                                                          'apellidoPaterno':request.session['apellidoPaterno']})
        
    except:
        return render(request, 'blog/index.html', {'adoptados':mascotas})

def formulario(request):
    if request.method =='POST':
        try:
            email = request.POST['email']
            rut = request.POST['username']
            password_1 = request.POST['password']


            b = User.objects.create_user(username =rut, password= password_1, email=email)
            b.save()

misitio/blog/templates/blog/base.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Page Title{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://www.gstatic.com/firebasejs/5.5.2/firebaseapp.js"></script> 
    <script src="https://www.gstatic.com/firebasejs/5.5.2/firebasemessaging.js"></script>
    

    {% block css_script %}
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    

</head>

<body>
    <header>
        <!-- menu -->
        <div class="row  limpiar">
            <div id="logo" class="col-md-6 limpiar ">
                <img id="logoPerro" src="{% static 'img/logo.png' %}" alt="logo">
            </div>
            <div class="col-md-6  limpiar">
                <nav class="row limpiar">
                    <div class="col-xs-12 col-md-auto ajusteLink">
                        
                        <a href="{% url 'blog:index' %}" >
                            Inicio
                        </a>
                        
                        
                    </div>
                   
                    <div class="col-xs-12 col-md-auto ajusteLink">
                        <a href="#">Quienes Somos</a>
                    </div>
                    <div class="col-xs-12 col-md-auto  ajusteLink">
                        <a href="#">Servicios</a>
                    </div>
                    <div class="col-xs-12 col-md-auto ajusteLink">
                        {% if nombre %}
                            
                        {% else %}
                            <a href="{% url 'blog:formulario' %}">Registro de usuario</a>
                        {% endif %}
                        
                    </div>
                    <div class="col-xs-12 col-md-auto ajusteLink">

                        {% if nombre%}
                            
                            <a href="{% url 'blog:usuario_success' %}">Usuario: {{nombre}} {{apellidoPaterno}}</a>
                        {% else %}
                             <a href="{% url 'blog:inicioSesion' %}">Inicio Sesión</a>

                        {% endif %}
                        
                    </div>

                </nav>
            </div>
        </div>
    </header>

    <section>
        

        {% block content%}

        {% block datosuser %}
        {% endblock %}
        
        {% endblock%}

    </section>

    {% block footer%}
    <!-- PIE DE PAGINA-->
    <footer>
        <h5>Desarrollo web y movil</h5>
        <p>
            <a href="http://jigsaw.w3.org/css-validator/check/referer">
                <img style="border:0;width:88px;height:31px" src="http://jigsaw.w3.org/css-validator/images/vcss" alt="¡CSS Válido!" />
            </a>
        </p>
    </footer>
    {% endblock%}

    
    
</body>

</html>

misitio/blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title%}
Index
{% endblock%}

{% block css_script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!----<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/index.css' %}" />
<link rel="stylesheet" href="{% static 'css/acercarImagenes.css' %}" />
{% endblock %}

{% block content %}

<body>
	<div class="container-fluid limpiar">

		<!-- CABECERA -->
		<header>
			<div class="row container-fluid limpiar">
				<div id="demo" class="carousel slide" data-ride="carousel">

					<!-- Indicators -->
					<ul class="carousel-indicators">
						<li data-target="#demo" data-slide-to="0" class="active"></li>
						<li data-target="#demo" data-slide-to="1"></li>
						<li data-target="#demo" data-slide-to="2"></li>
					</ul>

					<!-- The slideshow -->
					<div class="carousel-inner">
						<div class="carousel-item active">
							<img class="d-block w-100 imagenAjusteCarrosel" src="{% static 'imagenes/adoptados/Apolo.jpg' %}" alt="Perro Apolo"
							 style="width:100%">
							<div class="carousel-caption">
								<p class="colores">"Estamos felices de tener a Tom en casa.<br> Es un super fiel compañero."</p>
							</div>
						</div>
						<div class="carousel-item">
							<img class="d-block w-100 imagenAjusteCarrosel" src="{% static 'imagenes/adoptados/Duque.jpg' %}" alt="Perro Duque"
							 style="width:100%">
							<div class="carousel-caption">

								<p class="colores">"Estamos felices"</p>
							</div>
						</div>
						<div class="carousel-item">
							<img class="d-block w-100 imagenAjusteCarrosel" id="hrr" src="{% static 'imagenes/adoptados/Tom.jpg' %}" alt="Perro Tom"
							 style="width:100%">
							<div class="carousel-caption">

								<p class="colores">"Estamos felices"</p>
							</div>
						</div>
					</div>
					<!-- Left and right controls -->
					<a class="carousel-control-prev" href="#demo" data-slide="prev">
						<span class="carousel-control-prev-icon"></span>
					</a>
					<a class="carousel-control-next" href="#demo" data-slide="next">
						<span class="carousel-control-next-icon"></span>
					</a>
				</div>
			</div>

			<div id="sociales" class="row limpiar">
				<div class="col-md-4 d-none d-md-block">
					<p>{{idUsuario}}</p>
				</div>
				<div class="col-md-4 d-none d-md-block text-center">
					<p>Rescate y adopción de perros callejeros</p>
				</div>
				<div class="col-md-4">
					<div class="row limpiar">
						
						<div class="medida col-md-auto">
							<a href="#"><img src="{% static 'img/facebook.png' %}" alt="logo facebook"></a>
						</div>
						<div class="medida  col-md-auto">
							<img src="{% static 'img/google.png' %}" alt="logo google">
						</div>
						<div class="medida col-md-auto">
							<img src="{% static 'img/instagram.png' %}" alt="logo instagram">
						</div>
						<div class="medida  col-md-auto">
							<img src="{% static 'img/mail.png' %}" alt="logo mail">
						</div>
					</div>
				</div>
			</div>
		</header>

		<!-- CONTENIDO -->
		<section id="contenido" class="row limpiar">
			<article id="articulo1" class="col-12 col-md-6">
				<h1>RESCATE</h1>
				<h4>ETAPA UNO</h4>
				<hr>
				<p>Recatamos perros en situación de peligro y/o abandono. Los rehabilitamos y los preparamos para buscar un hogar.</p>
				<div>
					<img src="{% static 'img/rescate.jpg' %}" alt="rescatados">
				</div>
			</article>

			<article id="acticulo2" class="col-12 col-md-6">
				<div>
					<img src="{% static 'img/crowfunding.jpg' %}" alt="crowfunding">
				</div>
				<h1>CROWDFUNDING</h1>
				<h4>FINANCIAMIENTO</h4>
				<hr>
				<p>Sigue nuestras redes sociales para informarte acerca de las diversas campañas y actividades que realizamos para
					obtener un financiamiento y poder seguir ayudando.</p>
				<a class="botonCampanna" href="#">CAMPAÑAS</a>
			</article>
		</section>
		
		<!-- COLLAGE 1 -->
		<div id="collage" class="row">
			<div class="col-12">
					<h1 style="text-align:center;color: black;" >Galeria de Perritos</h1>
					{% if errorSolicitud %}
						{{errorSolicitud}}
					{% else %}
					{% endif%}
			</div>
			<div class="col-12">
					<div class="medida col-md-auto">
							<h3>Filtrado por:</h3>
						</div>
				<a href="{% url 'blog:filtroDisponibleIndex' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Disponible</a>
				<a href="{% url 'blog:filtroRescatadoIndex' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Rescatado</a>
				<a href="{% url 'blog:filtroAdoptadoIndex' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Adoptados</a>
			</div>
				
				
			{% if mascotas %}
			{% for m in mascotas %}
			<div class="col-12 col-md-4">

				<div class="card border-dark mb-3" style="max-width: 25rem;">
					<div class="card-header">Mascota: {{m.nombrePerro}}</div>
					<div class="card-body text-dark text-center">
						<h5 class="card-title">Raza: {{m.razaPredominante}}</h5>
						<p class="card-text"><img class="zoom" src="{{ MEDIA_URL}}{{m.file}}" alt=""></p>
						<p class="card-text">Descripción: {{m.descripcion}}</p>
					</div>
					<div class="card-footer bg-transparent border-success text-center">
						{% if m.estado == "Disponible"%}
							{% if nombre != "" %}
								<a class="btn btn-success btn-sm" href="{% url 'blog:validador2' m.id %}">Adoptalo ahora!</a>
							{% else %}
								<p>Inicia Sesion para adoptar</p>
							{% endif%}
							
						{% else%}
						<p>Estado: {{m.estado}}</p>
						{% endif%}
					</div>

				</div>

			</div>
			{% endfor %}
			{% endif%}

			{% if disponibles %}
			{% for m in disponibles %}
			<div class="col-12 col-md-4">

				<div class="card border-dark mb-3" style="max-width: 25rem;">
					<div class="card-header">Mascota: {{m.nombrePerro}}</div>
					<div class="card-body text-dark text-center">
						<h5 class="card-title">Raza: {{m.razaPredominante}}</h5>
						<p class="card-text"><img class="zoom" src="{{ MEDIA_URL}}{{m.file}}" alt=""></p>
						<p class="card-text">Descripción: {{m.descripcion}}</p>
					</div>
					<div class="card-footer bg-transparent border-success text-center">
						{% if m.estado == "Disponible"%}
							{% if nombre != "" %}
								<a class="btn btn-success btn-sm" href="{% url 'blog:validador2' m.id %}">Adoptalo ahora!</a>
							{% else %}
								<p>Inicia Sesion para adoptar</p>
							{% endif%}
							
						{% else%}
						<p>Estado: {{m.estado}}</p>
						{% endif%}
					</div>

				</div>

			</div>
			{% endfor %}
			{% endif%}

			
			{% if rescatados %}
			{% for m in rescatados %}
			<div class="col-12 col-md-4">

				<div class="card border-dark mb-3" style="max-width: 25rem;">
					<div class="card-header">Mascota: {{m.nombrePerro}}</div>
					<div class="card-body text-dark text-center">
						<h5 class="card-title">Raza: {{m.razaPredominante}}</h5>
						<p class="card-text"><img class="zoom" src="{{ MEDIA_URL}}{{m.file}}" alt=""></p>
						<p class="card-text">Descripción: {{m.descripcion}}</p>
					</div>
					<div class="card-footer bg-transparent border-success text-center">
						{% if m.estado == "Disponible"%}
							{% if nombre != "" %}
								<a class="btn btn-success btn-sm" href="{% url 'blog:validador2' m.id %}">Adoptalo ahora!</a>
							{% else %}
								<p>Inicia Sesion para adoptar</p>
							{% endif%}
							
						{% else%}
						<p>Estado: {{m.estado}}</p>
						{% endif%}
					</div>

				</div>

			</div>
			{% endfor %}
			{% endif%}

			{% if adoptados %}
			{% for m in adoptados %}
			<div class="col-12 col-md-4">

				<div class="card border-dark mb-3" style="max-width: 25rem;">
					<div class="card-header">Mascota: {{m.nombrePerro}}</div>
					<div class="card-body text-dark text-center">
						<h5 class="card-title">Raza: {{m.razaPredominante}}</h5>
						<p class="card-text"><img class="zoom" src="{{ MEDIA_URL}}{{m.file}}" alt=""></p>
						<p class="card-text">Descripción: {{m.descripcion}}</p>
					</div>
					<div class="card-footer bg-transparent border-success text-center">
						{% if m.estado == "Disponible"%}
							{% if nombre != "" %}
								<a class="btn btn-success btn-sm" href="{% url 'blog:validador2' m.id %}">Adoptalo ahora!</a>
							{% else %}
								<p>Inicia Sesion para adoptar</p>
							{% endif%}
							
						{% else%}
						<p>Estado: {{m.estado}}</p>
						{% endif%}
					</div>

				</div>

			</div>
			{% endfor %}
			{% endif%}


			
		</div>
	</div>

	<script src="{% static 'js/acercarImagenes.js' %}"></script>
</body>
{% endblock content %}

misitio/blog/templates/blog/respaldo_mantenedorIndex.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
</head>

<body>
    <div class="container">
        <div class="row">

            <div class="col-xs-12">
                <h1>Mantenedor Administrador</h1>

                <h4>{{ cuenta}}</h4>
                <h4>{{ nombre}}</h4>
                <h4>{{ apellidoPaterno}}</h4>

            </div>
            <div class="col-xs-12">
                <a href="{% url 'blog:agregarPerro' %}">Agregar Mascota</a>

            </div>
            <div class="col-xs-12">
                <a href="{% url 'blog:listarPerro' %}">Listar Mascota</a>

            </div>
            <div class="col-xs-12">
                <form method='POST' action="cerrarSeccion">
                    {% csrf_token %}
                    <input type="submit" value="Logout">
                </form>
            </div>

        </div>

    </div>

</body>

</html>